name: First Workflow

on:
  - push

jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps:
            - name: First Welcome Message
              run: echo "My first GitHu Actions Job"

            - name: List Files 
              run: ls -1a

            - name: Show Present Working Directory 
              run: pwd